### ISSUE TITLE
possible to make this shader work in GTAV?

### ISSUE THREAD

**Issue by kasuganosoras** [keroroxzz/CloudWorks#1]
Hi, I'm trying to install this shader in GTAV, but it doesn't work.

Is there any way to convert it? Thanks.

BTW, this is an awesome shader, I really like it. 😄

**Comment by keroroxzz** [comment]
It's my pleasure you like it.

Well, I know nothing about GTA V graphic mods, so it's hard to tell you how.
It's totally possible, but things supported only by DX9 and SA Enb pipeline should be adjusted.
Something like \<string UIName="V...."\>; and variables from line 16 to 36.

**Comment by kasuganosoras** [comment]
Thanks!
